[package]
name = "ic-wasi-polyfill"
version = "0.3.4"
authors = ["Stanislav Golubtsov <sgaflv@gmail.com>"]
edition = "2021"


[dependencies]
ic-cdk = "0.7.3"
ic-stable-structures = "0.5.3"
stable-fs = { git = "https://github.com/wasm-forge/stable-fs", rev = "970f298485ef76ee336ec6dc26bf81c69d023148" }
rand = "0.8.5"

[build]
target = "wasm32-wasi"

[lib]
crate-type = ["staticlib","lib"]
